server:
  port : 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.246.64:6432/test?autoReconnect=true
    username: ccs
    password: ccs

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: none
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: false
      javax.persistence.sharedCache.mode: NONE

