server:
  port : 8081

spring:
  data:
    mongodb:
      database: UsersNoSQLDatabase

  kafka:
    bootstrap-servers: localhost:9092 #29092 для docker-compose
    consumer:
      properties:
        isolation.level: read_committed # уровень изоляции для транзакций

values:
  nats:
    host: "192.168.246.64:4222"

